/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as brownieSol from "./brownie.sol";
export type { brownieSol };
import type * as tokenSol from "./token.sol";
export type { tokenSol };
